### ISSUE TITLE
Not working correctly with angularfire5

### ISSUE THREAD

**Issue by udarts** [pari-agsft/inventory-app#1]
I am trying to build my own app, based upon your inventory-app, but found out that your code is not using angularfire5. 

Can you update it so it is up-to-date with the latest versions of the plugins?

**Comment by pari-agsft** [comment]
I will try to port app to angulerfire5 in next week.
Thanks
Pari

**Comment by udarts** [comment]
Cool, thanks.

**Comment by udarts** [comment]
Any update on changing it to angularfire5?

**Comment by pari-agsft** [comment]
I have created a new branch - release/angular-5.
Code is working now but there are couple of fixes to be addressed.

1. CSS is not working - I will take a help from our UI team.
2. ApproveComponent - is not working. There are some changes in ng5 for data joins.
I will have a look at it sometime later. You can also check //FIXME code.

Make sure you uninstall firebase, angular/cli and angularfire2 before you run npm install.

Thanks
Pari

**Comment by udarts** [comment]
Hi there,

Thanks for your reply.
I noticed you use the deprecated version again. That doesn't seem to be the actual latest version. I have been trying that same thing, but wasn't the solution I was looking for. Was hoping to have the application in the actual latest version.

Cheers,

**Comment by pari-agsft** [comment]
Yes, I am using firebase-deprecated version. I have fixed the css and other issues.

I have created another branch refractor/angular-5. I will work on this branch to get things to the latest version.

Regards,
Pari

**Comment by pari-agsft** [comment]
I have committed the code changes in refractor/angular-5. We are almost there but still 3 FIXME to be addressed in inventory.service.ts

**Comment by pari-agsft** [comment]
Finally, it is resolved.
